version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.11.2
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run: docker build -f test/Dockerfile . -t test
      - run: docker run test